[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
scrollSepolia = "https://sepolia-rpc.scroll.io/"

# Etherscan verification settings are commented out to make them optional
# Uncomment when you want to verify contracts
# [etherscan]
# scrollSepolia = { key = "${SCROLLSCAN_API_KEY}", url = "https://api-sepolia.scrollscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
